title: The Microstructure Exchange
site:
  description: Something
  title: The Microstructure Exchange

# theme: jekyll-theme-cayman
github: 
  repository_url: https://github.com/cpfiffer/microstructure.exchange
  repository_name: microstructure.exchange
  owner_url: https://github.com/cpfiffer
  owner_name: Cameron Pfiffer

speaker-info:
  speaker-name: "Chester Spatt (Carnegie Mellon)"
  speaker-paper: "Dark Crypto"
  coauthors: "Thomas Ernst (Maryland), Bryan Routledge (Carnegie Mellon) and Ariel Zetlin-Jones (Carnegie Mellon)"
  speaker-date: "December 16, 11 a.m. (New York time)"
  paper-link: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5186551"
  #paper-link: "papers/Signaling.pdf" # If you have a file instead
  webinar-link: "https://us06web.zoom.us/j/84303454366?pwd=b4JaIdm1lx0w7n5vaMuYW1hWJ7YggF.1"
  # discussant: "Michael Noe (Eurex), Amit Goyal (SFI/Lausanne), and Eric Uhlmann (INSEAD)"
  # slides-link: /slides/RobinhoodSlides_TME.pdf
  abstract: "We study $550 billion in dark crypto trades: off-exchange trades which do not appear on any exchange dataset. These trades are proprietary to a large brokerage firm, which routes orders to a number of competing off-exchange wholesalers. Dark crypto liquidity frequently provides price improvement over and above a hypothetical NBBO, and we estimate customers save between $38 and $74 million per year. A lack of cryptocurrency regulation means the benefits of a cryptocurrency broker, and associated access to dark crypto liquidity, are not widely known."
